### ISSUE TITLE
Startup error after conversion to V2: ClassCastException

### ISSUE THREAD

**Issue by SlimeDog** [eldoriarpg/BigDoorOpener#17]
Spigot 1.16.1
BDO 2.0-BETA

Updated `config.yml` by hand from 1.2-BETA, based on file comparison. Here is the new one:
```
# dont touch it or at least dont complain when everything burns.
version: 1
# Get a simple notify, when a new build is available. Keeping this enabled is highly recommended
checkUpdates: false
# The refresh rate of the door state
refreshRate: 20
language: en_US
# The refresh rate of time changes in ticks. 1 sec = 20 ticks
timedRefreshRate: 20
# Help us improving this plugin by sending some anonymized metrics.
enableMetrics: false
# We save your doors. If it is empty you should change this :P
doors:
- ==: de.eldoria.bigdoorsopener.config.TimedDoor
  doorUID: '3'
  world: world_westeros
  position:
    ==: Vector
    x: 805.5
    y: 66.0
    z: -4577.0
  permission: ''
  ticksClose: 13000
  ticksOpen: 23750
  range: 0.0
  invertOpen: false
...
[more door definitions]
```

On start-up:
```
[11:42:49] [Server thread/INFO]: [BigDoorsOpener] Enabling BigDoorsOpener v2.0-BETA
[11:42:49] [Server thread/INFO]: [BigDoorsOpener] nashorn script engine started.

[11:42:49] [Server thread/INFO]: [BigDoorsOpener] World Guard found. Trying to get a hook.
[11:42:49] [Server thread/INFO]: [BigDoorsOpener] Hooked into world guard successfully.
[11:42:49] [Server thread/INFO]: [BigDoorsOpener] Config is up to date.
[11:42:49] [Server thread/ERROR]: Error occurred while enabling BigDoorsOpener v2.0-BETA (Is it up to date?)
java.lang.ClassCastException: class de.eldoria.bigdoorsopener.config.TimedDoor cannot be cast to class de.eldoria.bigdoorsopener.doors.ConditionalDoor (de.eldoria.bigdoorsopener.config.TimedDoor and de.eldoria.bigdoorsopener.doors.ConditionalDoor are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @15df3548)
        at de.eldoria.bigdoorsopener.config.Config.reloadConfig(Config.java:157) ~[?:?]
        at de.eldoria.bigdoorsopener.config.Config.loadConfig(Config.java:39) ~[?:?]
        at de.eldoria.bigdoorsopener.config.Config.<init>(Config.java:34) ~[?:?]
        at de.eldoria.bigdoorsopener.BigDoorsOpener.onEnable(BigDoorsOpener.java:94) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar-2020-07-11-1655:git-Spigot-c3a49df-b0c6dfe]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Nothing was changed in `config.yml`, so automatic conversion did not occur. And not surprisingly, doors do not actuate.

**Comment by RainbowDashLabs** [comment]
Yeah you did insert a version key.
The current version 0 is identified by a missing version key. when you remove it the config should be migrated to version 1.

**Comment by SlimeDog** [comment]
Thanks. Will try and update.

**Comment by SlimeDog** [comment]
I have only six doors. I decided to generate the BDO linkages from scratch. Works great!

**Comment by RainbowDashLabs** [comment]
Nice to hear. hope the new system makes it easier and less complicated
