### ISSUE TITLE
Error on plugin load

### ISSUE THREAD

**Issue by TNThacker2015** [eldoriarpg/BigDoorOpener#18]
Version: Spigot 1.16.1
When the plugin is initially loaded, it throws an error, which aborts the load.
```
[12:35:11 WARN]: Enabled plugin with unregistered PluginClassLoader BigDoorsOpener v2.0-BETA
[12:35:11 ERROR]: Error occurred while enabling BigDoorsOpener v2.0-BETA (Is it up to date?)
java.lang.IllegalArgumentException: --no-deprecation-warning
	at jdk.nashorn.internal.runtime.options.Options$ParsedArg.<init>(Options.java:702) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.options.Options.processArgList(Options.java:473) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.options.Options.process(Options.java:424) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.<init>(NashornScriptEngine.java:120) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngineFactory.newEngine(NashornScriptEngineFactory.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:195) ~[nashorn.jar:?]
	at de.eldoria.bigdoorsopener.util.CachingJSEngine.<init>(CachingJSEngine.java:26) ~[?:?]
	at de.eldoria.bigdoorsopener.BigDoorsOpener.onEnable(BigDoorsOpener.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-46]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-46]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-46]
	at net.Lenni0451.SpigotPluginManager.utils.PluginUtils.enablePlugin(PluginUtils.java:123) ~[?:?]
	at net.Lenni0451.SpigotPluginManager.commands.subs.Enable_Sub.execute(Enable_Sub.java:41) ~[?:?]
	at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.lambda$0(PluginManager_Command.java:103) ~[?:?]
	at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.onCommand(PluginManager_Command.java:113) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-46]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-46]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-46]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-46]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[12:35:11 INFO]: Disabling BigDoorsOpener v2.0-BETA

```

**Comment by RainbowDashLabs** [comment]
Already fixed this.
The new Version is already on Spigot please download it there.

**Comment by TNThacker2015** [comment]
Alright, thanks!
