### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mitchngwen** [eldoriarpg/BigDoorOpener#98]
Platform: Paper/Spigot/...
Version: running Paper version git-Paper-142 (MC: 1.19.2)

Big Doors Opener Version:
Big Doors Version: BigDoorsOpener version 2.4.2

[23:10:49] [Server thread/INFO]: [BigDoorsOpener] Hooked into Big Doors successfully.
[23:10:49] [Server thread/INFO]: [BigDoorsOpener] World Guard found. Trying to get a hook.
[23:10:49] [Server thread/INFO]: [BigDoorsOpener] Hooked into world guard successfully.
[23:10:49] [Server thread/INFO]: [BigDoorsOpener] Placeholder API found. Enabling placeholder usage.
[23:10:49] [Server thread/INFO]: [BigDoorsOpener] MythicMobs found. Enabling mythic mobs listener.
[23:10:49] [Server thread/ERROR]: [BigDoorsOpener] Plugin post start failed. Initializing failsave mode.
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.saveDefaultConfig()" because "this.plugin" is null
	at de.eldoria.bigdoorsopener.config.Config.updateConfig(Config.java:70) ~[BigDoorsOpener-2.4.2.jar:?]
	at de.eldoria.bigdoorsopener.config.Config.loadConfig(Config.java:65) ~[BigDoorsOpener-2.4.2.jar:?]
	at de.eldoria.bigdoorsopener.config.Config.<init>(Config.java:41) ~[BigDoorsOpener-2.4.2.jar:?]
	at de.eldoria.bigdoorsopener.core.BigDoorsOpener.onPostStart(BigDoorsOpener.java:145) ~[BigDoorsOpener-2.4.2.jar:?]
	at de.eldoria.bigdoorsopener.eldoutilities.plugin.EldoPlugin$1.run(EldoPlugin.java:185) ~[BigDoorsOpener-2.4.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-142]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mitchngwen** [comment]
hey kids I need a solution.

**Comment by RainbowDashLabs** [comment]
> hey kids I need a solution.

1. Have some patience. This is a free plugin and I am doing this in my spare time.
2. Don't call us "kids" we are grown adults. This is highly impolite and even insulting.
3. Please provide a full log file. Exceptions usually only make sense in the general context where they occur. Especially since I cant reproduce the error. Upload your log file or send a link created by `/bdo debug`.
4. If this error occurred after a reload of the server please know that reloading the server is discouraged in general.
